entrypoint: main.py
parameters:
  - name: SYSTEM_PROMPT
    kind: String
    default_value: 'Talk like Yoda always'
    required: true
  - name: SOMETHING_RANDOM
    kind: Number
    required: true
endpoints:
  - name: example-api
    protocol: Http
    port: 8181
